export default [
	{
		id: 'AA',
		title: 'Zonen',
		description: 'Welche Bereiche gibt es in den Park und welcher Funktionen haben sie?',
		active: false,
		path: 'layers/zonen.svg',
		color: '#1abc9c',
	},
	{
		id: 'BB',
		title: 'Müll',
		description: 'Wo ist welcher Art von Müll im Park zu sehen?',
		active: false,
		path: 'layers/muell.svg',
		color: '#3498db',
	},
	{
		id: 'CC',
		title: 'Aktivitäten',
		description: 'Wo werden welche Aktivitäten gemacht?',
		active: false,
		path: 'layers/aktivitaeten.svg',
		color: '#2ecc71',
	},
	{
		id: 'DD',
		title: 'Lärm',
		description: 'Wo im Park ist was zu hören?',
		active: false,
		path: 'layers/laerm.svg',
		color: '#9b59b6',
	},
	{
		id: 'EE',
		title: 'Alter',
		description: 'Welcher alter haben die Besucher des Parks und wo werden sie verteilt?',
		active: false,
		path: 'layers/alter.svg',
		color: '#e74c3c',
	},
	{
		id: 'FF',
		title: 'Ort Akzeptanz',
		description: 'Wo wird es gepflegt und wo nicht?',
		active: false,
		path: 'layers/ortakzeptanz.svg',
		color: '#34495e',
	},
	{
		id: 'GG',
		title: 'Vandalismusspuren',
		description: 'Wo kann man Vandalismusspuren sehen und von welcher Art?',
		active: false,
		path: 'layers/vandalismusspuren.svg',
		color: '#e67e22',
	},
];
