export default [
	{
		id: 'AA',
		title: 'Zonen',
		description: 'Welche Bereiche gibt es in den Park und welcher Funktionen haben sie?',
		active: false,
		path: 'layers/zonen.svg',
		color: '#1abc9c',
	},
	{
		id: 'DD',
		title: 'Lärm',
		description: 'Wo im Park ist wie laut?',
		active: false,
		path: 'layers/laerm.svg',
		color: '#E2001A',
	},
	// {
	// 	id: 'DD',
	// 	title: 'Ort Akzeptanz',
	// 	description: 'Wo wird es gepflegt und wo nicht?',
	// 	active: false,
	// 	path: 'layers/ortakzeptanz.svg',
	// 	color: '#34495e',
	// },
	{
		id: 'EE',
		title: 'Vandalismusspuren',
		description: 'Wo kann man Vandalismusspuren sehen und von welcher Art?',
		active: false,
		path: 'layers/vandalismusspuren.svg',
		color: '#e67e22',
	},
	{
		id: 'BB',
		title: 'Müll',
		description: 'Wo ist Müll im Park zu sehen?',
		active: false,
		path: 'layers/muell.svg',
		color: '#E5007E',
	},
	{
		id: 'CC',
		title: 'Alter',
		description: 'Welcher alter haben die Besucher des Parks und wo werden sie verteilt?',
		active: false,
		path: 'layers/alter.svg',
		color: '#3498db',
	},
	{
		id: 'FF',
		title: 'Aktivitäten',
		description: 'Wo werden welche Aktivitäten gemacht?',
		active: false,
		path: 'layers/aktivitaeten.svg',
		color: '#2ecc71',
	},
];
